; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "Winhance"
#define MyAppVersion ""
#define MyAppPublisher "Marco du Plessis"
#define MyAppURL "https://www.winhance.net/"
#define MyAppExeName "Winhance.exe"
#define MyAppAssocName MyAppName + " File"
#define MyAppAssocExt ".winhance"
#define MyAppAssocKey StringChange(MyAppAssocName, " ", "") + MyAppAssocExt

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{29282B88-03C4-430E-8A41-CF14F8186AD8}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppVerName=Winhance
SetupMutex=WinhanceSetupMutex,Global
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
UninstallDisplayIcon={app}\{#MyAppExeName}
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run
; on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the
; install be done in "64-bit mode" on x64 or Windows 11 on Arm,
; meaning it should use the native 64-bit Program Files directory and
; the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
ChangesAssociations=yes
DisableProgramGroupPage=yes
LicenseFile=C:\Winhance\LICENSE.txt
; Uncomment the following line to run in non administrative install mode (install for current user only).
;PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=dialog
OutputDir=C:\Winhance\installer-output
OutputBaseFilename=Winhance.Installer
SetupIconFile=C:\Winhance\src\Winhance.UI\Assets\AppIcons\winhance-rocket.ico
VersionInfoCopyright=Copyright © Marco du Plessis
SolidCompression=yes
WizardStyle=modern
; Dir page is replaced by a custom page that appears after task selection
DisableDirPage=yes
; Only create uninstaller for regular installations
Uninstallable=WizardIsTaskSelected('regularinstall')
; Close applications before installation/uninstallation
CloseApplications=yes
CloseApplicationsFilter=*{#MyAppExeName}
RestartIfNeededByRun=no

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Code]
function InitializeUninstall(): Boolean;
var
  ErrorCode: Integer;
begin
  Result := True;
  // Check if the application is running and ask to close it
  if CheckForMutexes('WinhanceSetupMutex') then
  begin
    if MsgBox('Winhance is currently running. Do you want to close it before uninstalling?', 
              mbConfirmation, MB_YESNO) = IDYES then
    begin
      // Try to close the application gracefully
      ShellExec('open', 'taskkill.exe', '/f /im {#MyAppExeName}', '', SW_HIDE, ewWaitUntilTerminated, ErrorCode);
    end;
  end;
end;

// Clean up old installation files while preserving user data
procedure CleanupOldInstallation;
var
  FindRec: TFindRec;
  OldInstallPath: String;
  ScriptsPath: String;
  HasScriptsFolder: Boolean;
begin
  OldInstallPath := ExpandConstant('{app}');
  ScriptsPath := OldInstallPath + '\Scripts';
  HasScriptsFolder := DirExists(ScriptsPath);
  
  // Only perform cleanup if this is an update (directory already exists)
  if DirExists(OldInstallPath) then
  begin
    // Delete all files in the root directory
    if FindFirst(OldInstallPath + '\*.*', FindRec) then
    begin
      try
        repeat
          if (FindRec.Attributes and FILE_ATTRIBUTE_DIRECTORY) = 0 then
            DeleteFile(OldInstallPath + '\' + FindRec.Name);
        until not FindNext(FindRec);
      finally
        FindClose(FindRec);
      end;
    end;
    
    // Delete all subdirectories except Scripts
    if FindFirst(OldInstallPath + '\*.*', FindRec) then
    begin
      try
        repeat
          if ((FindRec.Attributes and FILE_ATTRIBUTE_DIRECTORY) <> 0) and
             (FindRec.Name <> '.') and (FindRec.Name <> '..') and
             (CompareText(FindRec.Name, 'Scripts') <> 0) then
            DelTree(OldInstallPath + '\' + FindRec.Name, True, True, True);
        until not FindNext(FindRec);
      finally
        FindClose(FindRec);
      end;
    end;
  end;
end;

var
  CustomDirPage: TInputDirWizardPage;
  HasSetDefaultDir: Boolean;

procedure InitializeWizard;
begin
  HasSetDefaultDir := False;

  // Create a custom directory page that appears AFTER the tasks page
  CustomDirPage := CreateInputDirPage(wpSelectTasks,
    SetupMessage(msgWizardSelectDir),
    '',
    'To continue, click Next. If you would like to select a different folder, click Browse.',
    False, '');
  CustomDirPage.Add('');
  CustomDirPage.Values[0] := ExpandConstant('{autopf}\{#MyAppName}');
end;

// This function runs right before the actual installation starts
function PrepareToInstall(var NeedsRestart: Boolean): String;
begin
  NeedsRestart := False;
  // Clean up old installation files while preserving user data
  CleanupOldInstallation;
  Result := '';
end;

function NextButtonClick(CurPageID: Integer): Boolean;
begin
  Result := True;

  // After task selection, set the default directory based on installation type
  if CurPageID = wpSelectTasks then
  begin
    if not HasSetDefaultDir then
    begin
      HasSetDefaultDir := True;
      if WizardIsTaskSelected('portableinstall') then
        CustomDirPage.Values[0] := ExpandConstant('{userdesktop}\{#MyAppName}')
      else
        CustomDirPage.Values[0] := ExpandConstant('{autopf}\{#MyAppName}');
    end;
  end;

  // Sync the custom dir page value to the actual install directory.
  // Append \Winhance if the path doesn't already end with it.
  //
  // Silent-install handling (issue #649):
  //   - In-app updater (silent + /DIR=<current install path>): skip the sync,
  //     because the simulated Next-click would otherwise overwrite
  //     WizardForm.DirEdit.Text (and therefore {app}) with CustomDirPage.Values[0]
  //     ({autopf}\Winhance for regular, {userdesktop}\Winhance for portable),
  //     silently relocating the update.
  //   - Winhance.ps1 first-time install (silent, no /DIR=): keep the sync. The
  //     PS1 relies on it to redirect a portable install from DefaultDirName
  //     ({autopf}\Winhance) to {userdesktop}\Winhance.
  //   - Interactive install: keep the sync; the user may have edited the path
  //     on the custom dir page and it needs to flow back to {app}.
  if (CurPageID = CustomDirPage.ID) and ((not WizardSilent()) or (ExpandConstant('{param:DIR|}') = '')) then
  begin
    if CompareText(ExtractFileName(RemoveBackslashUnlessRoot(CustomDirPage.Values[0])), '{#MyAppName}') <> 0 then
      CustomDirPage.Values[0] := CustomDirPage.Values[0] + '\{#MyAppName}';
    WizardForm.DirEdit.Text := CustomDirPage.Values[0];
  end;
end;

[Tasks]
Name: "portableinstall"; Description: "Perform a portable installation"; GroupDescription: "Installation type:"; Flags: unchecked exclusive
Name: "regularinstall"; Description: "Perform a regular installation"; GroupDescription: "Installation type:"; Flags: exclusive
Name: "regularinstall\desktopicon"; Description: "Create a shortcut on the Desktop"; GroupDescription: "Additional shortcuts:"
Name: "regularinstall\startmenuicon"; Description: "Create a shortcut in the Start menu"; GroupDescription: "Additional shortcuts:"

[Files]
; All application files and subdirectories (recursive) - includes self-contained .NET runtime
; Excludes:
;  - "nul": a zero-byte file with a Windows reserved device name created by MSBuild
;  - onnxruntime.dll / DirectML.dll: ~38 MB (uncompressed) of Windows ML native
;    libraries that the Microsoft.WindowsAppSDK metapackage bundles into every
;    self-contained build. Winhance calls no ML/AI APIs, so they are dead weight -
;    excluding them makes the installer ~13 MB smaller. The metapackage can't be
;    slimmed at the NuGet level (icon/control packages depend on it); see
;    microsoft/WindowsAppSDK#5969.
Source: "C:\Winhance\src\Winhance.UI\bin\x64\Release\net10.0-windows10.0.19041.0\win-x64\*"; Excludes: "nul,onnxruntime.dll,DirectML.dll"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; Create a marker file for portable installations
Source: "C:\Winhance\extras\portable.marker"; DestDir: "{app}"; Flags: ignoreversion; Tasks: portableinstall
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Registry]
; Skip registry entries for portable installation
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocExt}\OpenWithProgids"; ValueType: string; ValueName: "{#MyAppAssocKey}"; ValueData: ""; Flags: uninsdeletevalue; Tasks: regularinstall
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}"; ValueType: string; ValueName: ""; ValueData: "{#MyAppAssocName}"; Flags: uninsdeletekey; Tasks: regularinstall
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\DefaultIcon"; ValueType: string; ValueName: ""; ValueData: "{app}\{#MyAppExeName},0"; Tasks: regularinstall
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\shell\open\command"; ValueType: string; ValueName: ""; ValueData: """{app}\{#MyAppExeName}"" ""%1"""; Tasks: regularinstall

[Icons]
; Create Start menu shortcut only if selected in tasks
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: regularinstall\startmenuicon
; Create desktop shortcut only if selected in tasks
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: regularinstall\desktopicon

[Run]
; Launch application after installation
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: shellexec nowait postinstall skipifsilent

[UninstallDelete]
; Delete all files and directories that might remain after uninstallation
Type: files; Name: "{app}\*.dll"
Type: files; Name: "{app}\*.exe"
Type: files; Name: "{app}\*.json"
Type: files; Name: "{app}\*.config"
Type: files; Name: "{app}\*.pdb"
Type: files; Name: "{app}\*.xml"
Type: files; Name: "{app}\*.log"
Type: filesandordirs; Name: "{app}\runtimes"
Type: filesandordirs; Name: "{app}\Scripts"
Type: filesandordirs; Name: "{app}\*"
Type: dirifempty; Name: "{app}"

